config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :jobs
  devise_for :users
  root 'home#index'
  resources :user_roles
  resources :companies
  resources :tech_stacks
  resources :home, only: [:index] do
    collection do
      get :about
      get :contact_us
    end
  end
  resources :admin,only: [:index] do
    collection do
      get :users_list
      get :user_roles_list
      get :companies
      get :tech_stacks
      get :jobs_list
    end
  end
  resources :business_developers,only: [:index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  has_many :users
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  belongs_to :user
  has_one_attached :poster
  belongs_to :tech_stack
end

app/models/tech_stack.rb
# frozen_string_literal: true

class TechStack < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable
  enum gender: { male: 0, female: 1, other: 2 }
  has_one_attached :profile_image
  belongs_to :user_role
  belongs_to :company
  has_many :jobs
  def is_admin?
    @user_role = UserRole.find(user_role_id)
    return true if @user_role.role_name.casecmp('admin').zero?

    false
  end

  def is_bd?
    @user_role = UserRole.find(user_role_id)
    return true if @user_role.role_name.casecmp('bussiness developer').zero?

    false
  end
end

app/models/user_role.rb
# frozen_string_literal: true

class UserRole < ApplicationRecord
  has_many :users
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  layout 'admin_dashboard'
  def index; end

  def users_list
    @users = User.all
  end

  def user_roles_list
    @user_roles = UserRole.all
  end

  def companies
    @companies = Company.all
  end

  def tech_stacks
    @tech_stacks = TechStack.all
  end

  def jobs_list
    @jobs  = Job.all
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[name gender email password
                                               profile_image user_role_id company_id])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name gender email
                                               profile_image user_role_id])
    devise_parameter_sanitizer.permit(:invite, keys: %i[name user_role_id gender profile_image])
  end
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  def create
    @company = Company.new(company_params)
    return unless @company.save

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @company = Company.find(params[:id])
    return unless @company.delete

    redirect_to companies_admin_index_path
  end

  private

  def company_params
    params.require(:company).permit(:name)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :redirect_user_dashaboard
  def index; end

  def about; end

  def contact_us; end

  private

  def redirect_user_dashaboard
    return unless current_user
    return unless current_user.is_admin?

    render template: 'admin/index', layout: 'admin_dashboard', formats: [:html]
  end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController < ApplicationController
  before_action :set_job, only: %i[show edit update destroy]

  # GET /jobs or /jobs.json
  def index
    @jobs = current_user.jobs
  end

  # GET /jobs/1 or /jobs/1.json
  def show; end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit; end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)
    @job.user = current_user
    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = Job.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def job_params
    params.require(:job).permit(:title, :description, :user_id, :tech_stack_id, :poster)
  end
end

app/controllers/user_roles_controller.rb
# frozen_string_literal: true

class UserRolesController < ApplicationController
  def create
    @role = UserRole.new(roles_params)
    return unless @role.save

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @user_role = UserRole.find(params[:id])
    return unless @user_role.delete

    redirect_to user_roles_list_admin_index_path
  end

  private

  def roles_params
    params.require(:user_role).permit(:role_name)
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
  def get_user_role_name_by_id(id)
    UserRole.find(id).role_name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_developer_helper.rb
# frozen_string_literal: true

module BusinessDeveloperHelper
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/jobs_helper.rb
# frozen_string_literal: true

module JobsHelper
end

app/helpers/tech_stacks_helper.rb
# frozen_string_literal: true

module TechStacksHelper
end

app/helpers/user_roles_helper.rb
# frozen_string_literal: true

module UserRolesHelper
end

app/views/admin/companies.html.erb
<div class="container py-5">
  <div class="row py-5 ">
    <div class="p-3 col-11 mx-auto tab-header d-flex align-item-center justify-content-between">
      <h3>User Roles</h3>
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addRoleModal">
        <i class="fa-solid fa-plus"></i> Register New Company
      </button>
    </div>
    <div class="p-3 col-11 mx-auto page-body">
      <div class="row p-0">
        <div class="col-4 ms-auto">
          <div class="input-group mb-3 ">
            <span class="input-group-text"><i class="fa-solid fa-magnifying-glass"></i></span>
            <input type="text" class="form-control" placeholder="search user here">
          </div>
        </div>
      </div>
      <div class="row p-0">
        <table class="table text-center table-striped">
          <thead class="bg-light">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Company Name</th>
              <th scope="col">Employess Count</th>
              <th></th>
            </tr>
          </thead>
          <tbody id="companies_table">
            <% if !@companies.blank? %>
              <% for company in @companies %>
                <tr>
                  <td class="col"><%= company.id %></td>
                  <td class="col"><%= company.name %></td>
                  <td class="col">
                    <%= company.users.count %>
                  </td>
                  <td class="col">
                    <%= link_to "Delete",company_path(company),method: :delete,class:'btn btn-danger'  %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<script>
  $('#companies_list').addClass('active');
</script>
<!-- Button trigger modal -->
<!-- Modal -->
<div class="modal  fade" id="addRoleModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="addRoleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addRoleModalLabel">Add New Company</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_for(Company.new,remote: true)  do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <label class="form-label"> Company Name </label>
            <%= f.text_field :name,class:"form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= f.submit 'Add Company',class:'btn btn-success' %>
        </div>
      </form>
    </div>
  </div>
</div>
<% end %>

app/views/admin/index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12">
      <h4>Hi Welcome Back</h4>
      <div class="row d-flex justify-content-between">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="card-link">Card link</a>
            <a href="#" class="card-link">Another link</a>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="card-link">Card link</a>
            <a href="#" class="card-link">Another link</a>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="card-link">Card link</a>
            <a href="#" clAass="card-link">Another link</a>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="card-link">Card link</a>
            <a href="#" class="card-link">Another link</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $('#home').addClass('active');
</script>

app/views/admin/jobs_list.html.erb
<div class="container py-5">
  <div class="row py-5 ">
    <div class="p-3 col-11 mx-auto tab-header d-flex align-item-center justify-content-between">
      <h3>All Jobs</h3>
    </div>
    <div class="p-3 col-11 mx-auto page-body">
      <div class="row p-0">
        <div class="col-4 ms-auto">
          <div class="input-group mb-3 ">
            <span class="input-group-text"><i class="fa-solid fa-magnifying-glass"></i></span>
            <input type="text" class="form-control" placeholder="search user here">
          </div>
        </div>
      </div>
      <div class="row p-0">
        <table class="table text-center table-striped">
          <thead class="bg-light">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Job Title</th>
              <th scope="col">Request Send</th>
              <th></th>
            </tr>
          </thead>
          <tbody id="role_table">
            <% if !@jobs.blank? %>
              <% for job in @jobs %>
                <tr>
                  <td class="col"><%= job.id %></td>
                  <td class="col"><%= job.title %></td>
                  <td class="col">0</td>
                  <td class="col">
                    <%= link_to "Delete",job_path(job),method: :delete,class:'btn btn-danger'  %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<script>
  $('#jobs_list').addClass('active');
</script>
<!-- Button trigger modal -->
<!-- Modal -->
<div class="modal  fade" id="addRoleModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="addRoleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addRoleModalLabel">Add New User Role</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_for(UserRole.new,remote: true)  do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <label class="form-label"> Role Name </label>
            <%= f.text_field :role_name,class:"form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= f.submit 'Add Role',class:'btn btn-success' %>
        </div>
      </form>
    </div>
  </div>
</div>
<% end %>

app/views/admin/tech_stacks.html.erb
<div class="container py-5">
  <div class="row py-5 ">
    <div class="p-3 col-11 mx-auto tab-header d-flex align-item-center justify-content-between">
      <h3>Tech Stacks</h3>
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addRoleModal">
        <i class="fa-solid fa-plus"></i> Add Tech Stack
      </button>
    </div>
    <div class="p-3 col-11 mx-auto page-body">
      <div class="row p-0">
        <div class="col-4 ms-auto">
          <div class="input-group mb-3 ">
            <span class="input-group-text"><i class="fa-solid fa-magnifying-glass"></i></span>
            <input type="text" class="form-control" placeholder="search user here">
          </div>
        </div>
      </div>
      <div class="row p-0">
        <table class="table text-center table-striped">
          <thead class="bg-light">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Stack Name</th>
              <th></th>
            </tr>
          </thead>
          <tbody id="companies_table">
            <% if !@tech_stacks.blank? %>
              <% for teck_stack in @tech_stacks %>
                <tr>
                  <td class="col"><%= teck_stack.id %></td>
                  <td class="col"><%= teck_stack.stack_name %></td>
                  <td class="col">
                    <%= link_to "Delete",tech_stack_path(teck_stack),method: :delete,class:'btn btn-danger'  %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<script>
  $('#tech_stacks_url').addClass('active');
</script>
<!-- Button trigger modal -->
<!-- Modal -->
<div class="modal  fade" id="addRoleModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="addRoleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addRoleModalLabel">Add New Stack</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_for(TechStack.new,remote: true)  do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <label class="form-label"> Stack Name </label>
            <%= f.text_field :stack_name,class:"form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= f.submit 'Add Company',class:'btn btn-success' %>
        </div>
      </form>
    </div>
  </div>
</div>
<% end %>

app/views/admin/user_roles_list.html.erb
<div class="container py-5">
  <div class="row py-5 ">
    <div class="p-3 col-11 mx-auto tab-header d-flex align-item-center justify-content-between">
      <h3>User Roles</h3>
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addRoleModal">
        <i class="fa-solid fa-plus"></i> New User Role
      </button>
    </div>
    <div class="p-3 col-11 mx-auto page-body">
      <div class="row p-0">
        <div class="col-4 ms-auto">
          <div class="input-group mb-3 ">
            <span class="input-group-text"><i class="fa-solid fa-magnifying-glass"></i></span>
            <input type="text" class="form-control" placeholder="search user here">
          </div>
        </div>
      </div>
      <div class="row p-0">
        <table class="table text-center table-striped">
          <thead class="bg-light">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Role Name</th>
              <th></th>
            </tr>
          </thead>
          <tbody id="role_table">
            <% if !@user_roles.blank? %>
              <% for user in @user_roles %>
                <tr>
                  <td class="col"><%= user.id %></td>
                  <td class="col"><%= user.role_name %></td>
                  <td class="col">
                    <%= link_to "Delete",user_role_path(user),method: :delete,class:'btn btn-danger'  %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<script>
  $('#roles_list').addClass('active');
</script>
<!-- Button trigger modal -->
<!-- Modal -->
<div class="modal  fade" id="addRoleModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="addRoleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addRoleModalLabel">Add New User Role</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_for(UserRole.new,remote: true)  do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <label class="form-label"> Role Name </label>
            <%= f.text_field :role_name,class:"form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= f.submit 'Add Role',class:'btn btn-success' %>
        </div>
      </form>
    </div>
  </div>
</div>
<% end %>

app/views/admin/users_list.html.erb
<div class="container py-5">
  <div class="row py-5 ">
    <div class="p-3 col-11 mx-auto tab-header d-flex align-item-center justify-content-between">
      <h3>Users</h3>
      <%= link_to (new_user_invitation_path) do  %>
        <i class="fa-solid fa-plus"></i> New User
      <% end %>
    </div>
    <div class="p-3 col-11 mx-auto page-body">
      <div class="row p-0">
        <div class="col-4 ms-auto">
          <div class="input-group mb-3 ">
            <span class="input-group-text"><i class="fa-solid fa-magnifying-glass"></i></span>
            <input type="text" class="form-control" placeholder="search user here">
          </div>
        </div>
      </div>
      <div class="row p-0">
        <table class="table">
          <thead class="bg-light">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Gender</th>
              <th scope="col">Role</th>
              <th scope="col">Invited</th>
              <th scope="col">Verified</th>
            </tr>
          </thead>
          <tbody>
            <% if !@users.blank? %>
              <% for user in @users %>
                <tr>
                  <td><%= user.id %></td>
                  <td><%= user.name %></td>
                  <td><%= user.gender %></td>
                  <td><%= get_user_role_name_by_id(user.user_role_id) %></td>
                  <td class="h6 text-<%= user.invited_to_sign_up? ? "success": "danger"%> "><%= user.invited_to_sign_up? %></td>
                  <td class="h6 text-<%= user.confirmed? ? "success": "danger"%> "><%= user.confirmed? %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<script>
  $('#user_list').addClass('active');
</script>

app/views/layouts/admin_dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/8da5cd2ad2.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <%= render 'shared/admin/navbar' %>
        <div class="col-2 sidebar bg-white">
          <%= render 'shared/admin/sidebar' %>
        </div>
        <div class="col-10 px-3 dashboard-body">
          <%= render 'shared/alerts' %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalesManagmentSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_alerts.html.erb
<% if notice %>
  <div class="alert position-fixed top-1 end-0 alert-warning alert-dismissible fade show" role="alert">
    <strong><%= notice %></strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% elsif alert %>
  <div class="alert position-fixed top-1 end-0 alert-danger alert-dismissible fade show" role="alert">
    <strong><%= alert %></strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to Rails.application.credentials[Rails.env.to_sym][:app_name], root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto col-12 mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home',root_path,class:'nav-link active'  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Jobs',jobs_path,class:'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to 'About US',about_home_index_path,class:'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact US',contact_us_home_index_path,class:'nav-link'  %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <% if current_user %>
          <li class="nav-item dropdown ms-auto">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= link_to "Logout", destroy_user_session_path,class:"dropdown-item", method: :delete  %></li>
            </ul>
          </li>
        <%else%>
          <%= link_to 'Login',new_user_session_path,class:'ms-auto me-2 btn btn-primary'  %>
          <%= link_to 'Sign up',new_user_registration_path,class:'me-2 btn btn-success'  %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/admin/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to Rails.application.credentials[Rails.env.to_sym][:app_name],root_path,class:'navbar-brand'  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if current_user %>
          <li class="nav-item dropdown ms-auto">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= link_to "Logout", destroy_user_session_path,class:"dropdown-item", method: :delete  %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/admin/_sidebar.html.erb
<ul class="nav flex-column">
  <li class="nav-item" id="home" >
    <%= link_to admin_index_path, class:'nav-link' do %>
      <i class="fa-solid fa-chart-line"></i> Dashboard
    <% end %>
  </li>
  <li class="nav-item" id="user_list">
    <%= link_to users_list_admin_index_path, class:'nav-link' do %>
      <i class="fa-solid fa-users"></i> Users
    <% end %>
  </li>
  <li class="nav-item" id="roles_list">
    <%= link_to user_roles_list_admin_index_path, class:'nav-link' do %>
      <i class="fa-solid fa-user-plus"></i> User Role
    <% end %>
  </li>
  <li class="nav-item" id="jobs_list">
    <%= link_to jobs_list_admin_index_path, class:'nav-link' do %>
      <i class="fa-solid fa-user-plus"></i> Jobs
    <% end %>
  </li>
  <li class="nav-item" id="companies_list">
    <%= link_to companies_admin_index_path, class:'nav-link' do %>
      <i class="fa-solid fa-building"></i> Comapanies
    <% end %>
  </li>
  <li class="nav-item" id="tech_stacks_url">
    <%= link_to tech_stacks_admin_index_path, class:'nav-link' do %>
      <i class="fa-solid fa-building"></i> Tech Stacks
    <% end %>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
  </li>
</ul>