config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :jobs
  devise_for :users
  root 'home#index'
  resources :user_roles
  resources :companies
  resources :tech_stacks
  resources :home, only: [:index] do
    collection do
      get :about
      get :contact_us
    end
  end
  resources :admin,only: [:index] do
    collection do
      get :users_list
      get :user_roles_list
      get :companies
      get :tech_stacks
      get :jobs_list
    end
  end
  resources :business_developers,only: [:index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  has_many :users
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  belongs_to :user
  has_one_attached :poster
  belongs_to :tech_stack
end

app/models/tech_stack.rb
# frozen_string_literal: true

class TechStack < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable
  enum gender: { male: 0, female: 1, other: 2 }
  has_one_attached :profile_image
  belongs_to :user_role
  belongs_to :company
  has_many :jobs
  def is_admin?
    @user_role = UserRole.find(user_role_id)
    return true if @user_role.role_name.casecmp('admin').zero?

    false
  end

  def is_bd?
    @user_role = UserRole.find(user_role_id)
    return true if @user_role.role_name.casecmp('bussiness developer').zero?

    false
  end
end

app/models/user_role.rb
# frozen_string_literal: true

class UserRole < ApplicationRecord
  has_many :users
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  layout 'admin_dashboard'
  def index; end

  def users_list
    @users = User.all
  end

  def user_roles_list
    @user_roles = UserRole.all
  end

  def companies
    @companies = Company.all
  end

  def tech_stacks
    @tech_stacks = TechStack.all
  end

  def jobs_list
    @jobs  = Job.all
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[name gender email password
                                               profile_image user_role_id company_id])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name gender email
                                               profile_image user_role_id])
    devise_parameter_sanitizer.permit(:invite, keys: %i[name user_role_id gender profile_image])
  end
end

app/controllers/business_developer_controller.rb
# frozen_string_literal: true

class BusinessDeveloperController < ApplicationController
  def index
  end
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  def create
    @company = Company.new(company_params)
    return unless @company.save

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @company = Company.find(params[:id])
    return unless @company.delete

    redirect_to companies_admin_index_path
  end

  private

  def company_params
    params.require(:company).permit(:name)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :redirect_user_dashaboard
  def index; end

  def about; end

  def contact_us; end

  private

  def redirect_user_dashaboard
    return unless current_user
    return unless current_user.is_admin?

    render template: 'admin/index', layout: 'admin_dashboard', formats: [:html]
  end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController < ApplicationController
  before_action :set_job, only: %i[show edit update destroy]

  # GET /jobs or /jobs.json
  def index
    @jobs = current_user.jobs
  end

  # GET /jobs/1 or /jobs/1.json
  def show; end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit; end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)
    @job.user = current_user
    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = Job.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def job_params
    params.require(:job).permit(:title, :description, :user_id, :tech_stack_id, :poster)
  end
end

app/controllers/tech_stacks_controller.rb
# frozen_string_literal: true

class TechStacksController < ApplicationController
  def create
    @stack = TechStack.new(tech_stacks_params)
    return unless @stack.save

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @stack = TechStack.find(params[:id])
    return unless @stack.delete

    redirect_to tech_stacks_admin_index_path
  end

  private

  def tech_stacks_params
    params.require(:tech_stack).permit(:stack_name)
  end
end

app/controllers/user_roles_controller.rb
# frozen_string_literal: true

class UserRolesController < ApplicationController
  def create
    @role = UserRole.new(roles_params)
    return unless @role.save

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @user_role = UserRole.find(params[:id])
    return unless @user_role.delete

    redirect_to user_roles_list_admin_index_path
  end

  private

  def roles_params
    params.require(:user_role).permit(:role_name)
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
  def get_user_role_name_by_id(id)
    UserRole.find(id).role_name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_developer_helper.rb
# frozen_string_literal: true

module BusinessDeveloperHelper
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/jobs_helper.rb
# frozen_string_literal: true

module JobsHelper
end

app/helpers/tech_stacks_helper.rb
# frozen_string_literal: true

module TechStacksHelper
end

app/helpers/user_roles_helper.rb
# frozen_string_literal: true

module UserRolesHelper
end

app/views/business_developer/index.html.erb
<h1>bd</h1>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/contact_us.html.erb
<h1>Home#contact_us</h1>
<p>Find me in app/views/home/contact_us.html.erb</p>

app/views/home/index.html.erb
<h1 class="text-center">Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<% if current_user %>
  <%= link_to "Add New User",new_user_invitation_path,class:'btn btn-outline-success'  %>
<% end %>

app/views/jobs/_form.html.erb
<div class="col-lg-3 col-12 mx-auto">
  <%= form_with(model: job, local: true) do |form| %>
    <% if job.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>
        <ul>
          <% job.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group mb-2 ">
      <%= form.label :title,class:'form-label' %>
      <%= form.text_field :title,class:'form-control' %>
    </div>
    <div class="form-group mb-2 ">
      <%= form.label :poster,"Job Poster",class:'form-label' %>
      <%= form.file_field :poster,class:'form-control' %>
    </div>
    <div class="form-group mb-2 ">
      <%= form.label :tech_stack_id,'Company Name', class:'formorm-label' %>
      <%= form.select(:tech_stack_id, options_from_collection_for_select(TechStack.all, :id, :stack_name),{},{class:'form-select'}) %>
    </div>
    <div class="form-group mb-2 ">
      <%= form.label :description,class:'form-label' %>
      <%= form.text_area :description,class:'form-control' %>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/jobs/_job.html.erb
<div class="card col-3 me-2" style="width: 18rem;">
  <% if job.poster.attached? %>
    <%= image_tag job.poster, alt: "poster",class:"card-img-top poster-img " %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= job.title %></h5>
    <p class="card-text"><%= job.description %></p>
    <%= link_to 'Details', job_path(job),class:'btn btn-primary' %>
  </div>
</div>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Jobs</h1>
  <div class="jobs d-flex row">
    <%= render @jobs %>
  </div>
  <br>
  <%= link_to 'New Job', new_job_path %>
</div>

app/views/jobs/new.html.erb
<div class="container mt-5">
  <div class="row">
    <h1 class="text-center">New Job</h1>
    <%= render 'form', job: @job %>
    <%= link_to 'Back', jobs_path %>
  </div>
</div>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>
<% if @job.poster.attached? %>
  <%= image_tag @job.poster, alt: "text" %>
<% end %>
<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>
<p>
  <strong>User:</strong>
  <%= @job.user.name %>
</p>
<p>
  <strong>Tech stack:</strong>
  <%= @job.tech_stack.stack_name %>
</p>
<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/tech_stacks/create.js.erb
$("#addRoleModal").modal("hide");
$("#companies_table").append(`<tr><td><%= @stack.id%></td><td><%= @stack.stack_name%></td>
<td><%= link_to "Delete",tech_stack _path(@stack),method: :delete,class:'btn btn-danger'%></td></tr>`)

app/views/user_roles/create.js.erb
$("#addRoleModal").modal("hide");
$("#role_table").append(`<tr><td><%= @role.id%></td><td><%= @role.role_name%></td><td><%= link_to "Delete",user_role_path(@role),method: :delete,class:'btn btn-danger'%></td></tr>`)